name: flutter_candies_demo_library
description:  package library for demo of flutter candies, it provides core classes.
version: 1.0.0
author: zmtzawqlp <zmtzawqlp@live.com>
homepage: https://github.com/fluttercandies/flutter_candies_demo_library

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  loading_more_list_library: any
  http_client_helper: any  
  extended_image: any  
  pull_to_refresh_notification: any
  extended_text: ^1.0.1
  like_button: any
  
  #image_picker_saver: 0.3.0
  photo_manager: any
  url_launcher: 5.3.0
  intl: ^0.15.7
  oktoast: ^2.1.4
dependency_overrides:
  extended_text_library:
    git:
      url: https://github.com/masewo/extended_text_library.git
dev_dependencies:
  ff_annotation_route: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
      - assets/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
